# need docker
# build with Dockerfile.dev
# tell how to run test suite
# tell how to deploy to aws

sudo: required
language: generic
services:
  - docker

before_install:
  - docker build  -t matthewbouchard/docker-workflow -f Dockerfile.dev .
script:
  - docker run -e CI=true matthewbouchard/docker-workflow npm run test
 